### PR TITLE
Update for v.4.0.0

### PR DESCRIPTION
**Pull request by DenB10**
Phew! Done!
But I would like to translate some additional words if possible:
- In the settings page: "default" (Markers tab), "Marker" (M, 2, 3) and "Shift" (Shortcuts tab), Textmarker "on" Github (icon tooltip), Textmarker "by" underflyingbirches.
- In the sidebar: "tag" placeholder.
I also signal an error in the addon-page.html file: "subnav_settings_mark" instead "subnav_settings_history" on line 70.

PS: Congratulations for this version. Textmarker becomes a highlighting jewel ;)

### CODE REVIEW

**Comment by ufb** [comment]
Nice:)
I will prepare the fields for "default", "Marker", "Shift", "on", "by" and "tag" and look into the "  subnav_settings_mark"-bug tomorrow

> Textmarker becomes a highlighting jewel

Hope I found all important bugs and won't break anything!

**Comment by ufb** [comment]
Pushed the changes -> last 2 commits. Lines 61-65.
Merci beaucoup:)
Did it work so far and did your history persist on 4.0.0?

**Comment by DenB10** [comment]
> Did it work so far and did your history persist on 4.0.0?
Yes, I'm testing and it seems to work so far...

> Pushed the changes -> last 2 commits. Lines 61-65.
Problems : 
- only "default" appears to be well translated
- "Marker" is not translated in the column Context menu at the tab Shortcuts. In the column Keyboard shortcuts, it is not correctly translated because the word appears in the plural (Surligneurs instead Surligneur).

**Comment by ufb** [comment]
fixed and pushed

**Comment by DenB10** [comment]
No, 'by', 'on', 'tag', 'Shift' are not translated!

**Comment by ufb** [comment]
oh, I actually did it already, but must have been reverted when I pulled your commit(?)
'by', 'on' and 'tag' should be there now, 'Shift' was already there, so I don't know why 'Shift' is not working for you :(

**Comment by ufb** [comment]
ah no, hold on.. I see the problem now. I had `<span data-l10n-id="shift">Shift</span>` in the markup, but should have been `<span data-l10n-id="shift"></span>`. Didnt recognize it, because I dont translate "Shift" for the German version.

**Comment by ufb** [comment]
So, the problem is also that the script responsible for the l10n-converting is using `querySelectorAll` to find all elements with l10n-id, but it won't find encapsulated elements withing `<option>` elements. So the only solution would be to give all 31 option elements an l10n-id, where the corresp. message values hold the complete text content of those options - so instead of one `"shift":{"message":"Shift"}` we would need 31 messages (Shift + M, Ctrl + Shift + 3, ...)
Maybe we can do that for next version - I hope French users will understand the word "Shift" ;-)

**Comment by ufb** [comment]
Alternatively you can just translate "shift" and I add a small JS function that is replacing all text contents of options that include the word "Shift" with the l10n-translation;) Thats seems better than adding 31 messages to 3 files just for one word. I can do that tomorrow

**Comment by DenB10** [comment]
Don't split your hairs, of course everybody understands the word 'Shift'. Let it so, too much work for nothing :)

**Pull request merged**
