### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by DenB10**

### CODE REVIEW

**Comment by ufb** [comment]
cool thanks! I'm still busy with testing / bug fixing, but pretty confident to get it done by tonight or tomorrow latest..

**Comment by DenB10** [comment]
Hang in there!

**Comment by ufb** [comment]
@DenB10 Hi Den, how are you doing?
I'm planning on releasing a new version soon (in 1 or 2 weeks). Would you be up to translating the new texts? It's quite a lot, so if it's too much then no problem, there are still not so many French speakers using Textmarker.

Here the list of new text keys (added the physical location in brackets, so you'd know where to find the text in the app):
ctx_c			[ context menu item: copy ]
attr_1b			[ search input on history page (only visible with >3 entries) ]
h461			[ header Settings > Notes ]
t448c			[ Settings > Notes ]
js_injection_failure	[ Notification ]
css_injection_failure	[ Notification ]
error_save_autocs	[ Notification ]
error_save_iframes	[ Notification ]
t211			[ Manual > Short introduction ]
h445			[ Settings > Misc ]
t4413			[ Settings > Misc ]
t4414			[ Settings > Misc ]
t4415			[ Settings > Misc ]
t4416			[ Settings > Misc ]
t458			[ Settings > Notifications ]
t459			[ Settings > Notifications ]
t4510			[ Settings > Notifications ]
t913			[ Syncing ]
t917			[ Syncing ]
t918			[ Syncing ]
t919			[ Syncing ]
tbb_mitem_10		[ Dropdown Menu in Navigationbar ]
tbb_pause_true		[ Dropdown Menu in Navigationbar ]
tbb_pause_false		[ Dropdown Menu in Navigationbar ]
broken_entry		[ History page, if an entry has incorrect shape ]
sb08			[ Sidebar last tab ]
sb76			[ Sidebar > Links ]
sb81			[ Sidebar > Themes ]
sb82			[ Sidebar > Themes ]
sb83			[ Sidebar > Themes ]
troubleshooting		[ On Textmarker pages: Nav > between Contact and Error Logs ]
true			[ Troubeshooting ]
false			[ Troubeshooting ]
hA0-tA171		[ Troubeshooting ]
h1112-h1125		[ News ]

**Comment by DenB10** [comment]
I'm fine, thanks. And you, how are you? Is it as hot where you are as it is here (38°C)?

> I'm planning on releasing a new version soon (in 1 or 2 weeks). Would you be up to translating the new texts? It's quite a lot, so if it's too much then no problem, there are still not so many French speakers using Textmarker.

So, I take a look and I get down to work... for the **countless** French users :)
Thank you for your explanations ;)

**Comment by ufb** [comment]
I'm doing good - planning this new release for a long time now, but was busy with work and life.
Yesterday we had 38°C too, but today it's freezingly cold: only 27° ;) Will raise up to 38 again though this Sunday.
Thanks a lot for your help and don't worry if it's too much, the fallback will be English. By far the most new texts are on the new Troubleshooting page, so if this stays in English for now it wouldn't be such a big deal, because users can also just write me an e-mail to get help;)

**Pull request merged**
