### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by DenB10**

### CODE REVIEW

**Comment by ufb** [comment]
merci!
I see, my French is not sufficient - but I tried ;)

**Comment by DenB10** [comment]
Your French is not so bad ! Just a bit lesser than your German :-)

**Comment by ufb** [comment]
Hi Den,
I added some features and would upload the new version soon.
I did some French translations myself, but not the long ones for the News page (h114, h115, t114, t115).
If you'd like to translate then I won't publish until tomorrow ;)

**Comment by DenB10** [comment]
Done!

**Pull request merged**
