### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by DenB10**

### CODE REVIEW

**Comment by ufb** [comment]
@DenB10 Hi there, in about a week I'm going to release a major update, version 4.0.0. There is a lot of new text content. I left the message fields blank in the French localization file, so searching for `"message":""` will work to find all non-tranlated texts. Don't worry if that's too much to do in such a short time - French users will see the English default texts then ;)

**Comment by DenB10** [comment]
Hi ufb, I'll do my best ;)
Note: an error on line "note_restoration_failure_reason_2" (and 3) in the English file? For "meat", do you rather mean "meet"? Ich verstehe nicht warum es gibt Fleisch im Satz :)

**Comment by ufb** [comment]
hahah, you are right, der Satz sollte eigentlich vegetarisch sein^^
Merci:)

**Comment by DenB10** [comment]
The translation progresses slowly, I encounter some difficulties testing new features to adjust my translations:
1) "Unable to migrate your settings and history" error message when installing new version -> I must uninstall and then reinstall Textmarker 4 for it to work.
2) It's impossible to expand or collapse sidebar headers. Whenever I click on the plus/minus buttons, the same entry appears in the error log: "TypeError: id is null [sidebar:1352:9]".
Are those bugs in Textmarker or by me?

**Comment by ufb** [comment]
Oh, how did you install 4.0.0? I didn't think you'd try to do that - I never push the build until just before the release

**Comment by ufb** [comment]
Did you package it yourself using `web-ext` or did you zip the extension folder or how did you manage to get it installed?

**Comment by ufb** [comment]
If you like I can push the temporary build to the master branch - or if you cloned the repo and using `web-ext` you can run `web-ext build`

**Comment by DenB10** [comment]
I always do so: I download the master file from code tab, then extract the extension folder and finally rezip as xpi. 
Note: it's important to test an extension to avoid bad translation!

**Comment by ufb** [comment]
>  it's important to test an extension to avoid bad translation

I understand
OK, let me quickly push the build. This is packaging everything that is in the `src` folder to the `extension` folder. The extension folder holds everything needed for creating the `xpi`

**Comment by DenB10** [comment]
Thank you :)

**Comment by ufb** [comment]
done. I hope that your history didn't get messed up already :/

**Comment by ufb** [comment]
Now that I know how you proceed I will first finish the complete build up to the point where I think the version is stable, before asking you for translations -> I really didn't want to risk that your saved highlights get lost or something like that - sorry

**Comment by DenB10** [comment]
Of course my history was totally messed, but I always back up my profile, so no problem!

**Comment by ufb** [comment]
phew, thats good :)

**Pull request merged**
