### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by DenB10**
Excuse me for the delay, I haven't see the email.

### CODE REVIEW

**Comment by ufb** [comment]
Thanks :)
Now a big break from Textmarker and enjoying the summer^^

**Comment by ufb** [comment]
@DenB10 
Hi, unfortunately I had to keep struggling with this annoying APIs and this permission mess past few days. I think I came up with a good solution now, but there are 2 more texts added and 1 changed:
t816
missing_permission_wn
t817
I will do some more testing and then release 5.1.0

**Comment by DenB10** [comment]
Done!
P.S.: I thought it was respite during the summer time?

**Comment by ufb** [comment]
Yes, but had to fix things :/
I hope that it's all running OK now - I wish you a nice week :)

**Pull request merged**
